sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "nightly" # currently points to 3.7-dev
install: pip install pytest pytest-cov coveralls
script: pytest -v --cov=carpo/ test/ 
after_success:
  - coveralls
